server:
  port: 8080
spring:
  http:
    converters:
      string-encoding-charset: UTF-8
  application:
    name: obsluga-leadow
fakturaxl:
  tokenStormedge: ${FAKTURA_XL_TOKEN_STORMEDGE:?FAKTURA_XL_TOKEN_STORMEDGE is required}
  tokenKaras: ${FAKTURA_XL_TOKEN_KARAS:?FAKTURA_XL_TOKEN_KARAS is required}
bitrix:
  url: ${BITRIX_URL:? BITRIX_TOKEN is required}
